In [ ]:
a = 1

In [ ]:
import time

<module 'time' (built-in)>

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [ ]:
def my_adder(a, b, c):

#this is the summation
  out = a + b + c

  return out

In [ ]:
my_adder(1,2,3)

6

In [ ]:
def my_thermo_stat(temp, desired_temp):
  if temp < desired_temp - 5:
    status = 'Heat'
  elif temp > desired_temp + 5:
    status = 'AC'
  else:
    status = 'Off'
  return status

In [ ]:
x = 3
y = 7
z = 9

A = 2 * x + 3 * x + 12
B = 4 * x + 3 * x * y - 10 * y
C = 12 * z + (3 * x * y * z * 16 * y) + 32
D = 4 * z + 25 * y + 14 * x * y / 4
E = 5 * y + 26 * z * x - 20 * x * y / 3
F = ([3, 4, 5])
G = np.array ([[2, 4],[6, 8]])

print("\n", A,"\n", B,"\n", C,"\n", D,"\n", E,"\n", F,"\n",G)


 27 
 5 
 63644 
 284.5 
 597.0 
 [3, 4, 5] 
 [[2 4]
 [6 8]]


In [ ]:
import numpy as np
a = [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]

# find diagonal cefficients
diag = np.diag(np.abs(a))

#find row sum without diagonal
off_diag = np.sum(np.abs(a), axis = 1) - diag

if np.all (diag > off_diag) :
    print(' matrix is diagonally dominant')
else:
    print('Not diagonally dominant')

 matrix is diagonally dominant


In [ ]:
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.001
converged = False

x_old = np.array([x1, x2, x3])

print('Iteration results')
print(' k,  x1,   x2,   x3 ')
for k in range(1, 50):
    x1 = (14-3*x2+3*x3) / 8
    x2 = (5+2*x1-5*x3) / (-8)
    x3 = (-8-3*x1-5*x2) / (10)
    x = np.array([x1, x2, x3])
    #check if it is smaller than threshold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))

    print("%d, %.4f, %.4f, %.4f"%(k, x1, x2, x3))
    if dx < epsilon:
      converged = True
      print('Converged!')
      break

    #assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')


Iteration results
 k,  x1,   x2,   x3 
1, 1.7500, -1.0625, -0.7937
2, 1.8508, -1.5838, -0.5633
3, 2.1327, -1.5103, -0.6847
4, 2.0596, -1.5678, -0.6340
5, 2.1002, -1.5463, -0.6569
6, 2.0835, -1.5565, -0.6468
7, 2.0911, -1.5520, -0.6513
8, 2.0878, -1.5540, -0.6493
9, 2.0893, -1.5531, -0.6502
10, 2.0886, -1.5535, -0.6498
Converged!


In [ ]:
import numpy as np

A = np.array([[4, 3, -5],
             [-2, -4, 5],
             [8, 8, 0]])

y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


Exercise session 2

Soal 1

In [ ]:
# 1.
import numpy as np

a = np.array([[13, 5, -7],
              [0, 1, 6],
              [-2, 5, 4]])

#find diagonal coefficients
diag = np.diag(np.abs(a))

#find row sum without diagonal
off_diag = np.sum(np.abs(a), axis = 1) - diag

if np.all (diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('Not diagonally dominant')

#for converge
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.1
converged = False

x_old = np.array([x1, x2, x3])

for k in range(1, 50):
    x1 = (18-5*x2+7*x3) / 13
    x2 = (16-0*x1-6*x3) / 1
    x3 = (23+2*x1-5*x2) / 4
    x = np.array([x1, x2, x3])
    #check if it is smaller than thresholdw
    dx = np.sqrt(np.dot(x - x_old, x - x_old))

    if dx < epsilon:
        converged = True
        print('Converged!')
        break

    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')


# for linear algebra
b = np.array([18, 16, 23])

c = np.linalg.solve(a, b)
print(c)

Not diagonally dominant
Not converge, increase the # of iterations
[1.20631068 3.40291262 2.09951456]


Soal 2

In [ ]:
# 2.
import numpy as np

a = np.array([[-6, 3, 1],
              [5, 7, 1],
              [4, 6, -12]])

#find diagonal coefficients
diag = np.diag(np.abs(a))

#find row sum without diagonal
off_diag = np.sum(np.abs(a), axis = 1) - diag

if np.all (diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('Not diagonally dominant')

#for converge
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.03
converged = False

x_old = np.array([x1, x2, x3])

for k in range(1, 50):
    x1 = (6-3*x2+1*x3) / (-6)
    x2 = (8-5*x1-1*x3) / 7
    x3 = (4-4*x1-6*x2) / (-12)
    x = np.array([x1, x2, x3])
    #check if it is smaller than thresholdw
    dx = np.sqrt(np.dot(x - x_old, x - x_old))

    if dx < epsilon:
        converged = True
        print('Converged!')
        break

    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')


# for linear algebra
b = np.array([6, 8, 4])

c = np.linalg.solve(a, b)
print(c)

matrix is diagonally dominant
Converged!
[-0.29972752  1.32425068  0.22888283]


Soal 3

In [ ]:
# 3
import numpy as np

a = np.array([[-3, -5, -7],
              [2, 6, -8],
              [4, 5, 3]])

#find diagonal coefficients
diag = np.diag(np.abs(a))

#find row sum without diagonal
off_diag = np.sum(np.abs(a), axis = 1) - diag

if np.all (diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('Not diagonally dominant')

#for converge
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.001
converged = False

x_old = np.array([x1, x2, x3])

for k in range(1, 50):
    x1 = (11+5*x2+7*x3) / (-3)
    x2 = (9-2*x1+8*x3) / 6
    x3 = (6-4*x1-5*x2) / 3
    x = np.array([x1, x2, x3])
    #check if it is smaller than thresholdw
    dx = np.sqrt(np.dot(x - x_old, x - x_old))

    if dx < epsilon:
        converged = True
        print('Converged!')
        break

    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')


# for linear algebra
b = np.array([11, 9, 6])

c = np.linalg.solve(a, b)
print(c)

Not diagonally dominant
Not converge, increase the # of iterations
[ 8.33333333 -4.16666667 -2.16666667]


Soal 4

In [ ]:
#4

import numpy as np

a = np.array([[8, 2, -4],
              [0, 6, 1],
              [5, 3, -10]])

#find diagonal coefficients
diag = np.diag(np.abs(a))

#find row sum without diagonal
off_diag = np.sum(np.abs(a), axis = 1) - diag

if np.all (diag > off_diag):
    print('matrix is diagonally dominant')
else:
    print('Not diagonally dominant')

#for converge
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.2
converged = False

x_old = np.array([x1, x2, x3])

for k in range(1, 50):
    x1 = (12-2*x2+4*x3) / 8
    x2 = (7-0*x1-1*x3) / 6
    x3 = (8-5*x1-3*x2) / (-10)
    x = np.array([x1, x2, x3])
    #check if it is smaller than thresholdw
    dx = np.sqrt(np.dot(x - x_old, x - x_old))

    if dx < epsilon:
        converged = True
        print('Converged!')
        break

    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')


# for linear algebra
b = np.array([12, 7, 8])

c = np.linalg.solve(a, b)
print(c)

matrix is diagonally dominant
Converged!
[1.31550802 1.13368984 0.19786096]


**Session 3**

Power Method

In [ ]:
import numpy as np
def normalize(x):
    fac = abs(x).max()
    x_n = x / x.max()
    return fac, x_n
x = np.array([1, 1])
a = np.array([[0, 2],
             [2, 3]])
for i in range(8):
    x = np.dot(a, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 3.999949137887188
Eigenvector: [0.50000636 1.        ]


Invers Power Method

In [ ]:
from numpy.linalg import inv
a_inv = inv(a)

for i in range(8):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 0.20000000000024853
Eigenvector: [1. 1.]


Calculate the eigenvalues and eigenvectors for matrix A

In [ ]:
import numpy as np
from numpy.linalg import eig
a = np.array([[0, 2],
              [2, 3]])
w,v = eig(a)
print('E-Value:', w)
print('E-Vector:', v)

E-Value: [-1.  4.]
E-Vector: [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


Compute the eigenvalue and eigenvector for matrix A

In [ ]:
import numpy as np
from numpy.linalg import eig
a = np.array([[2, 2, 4],
              [1, 3, 5],
              [2, 3, 4]])
w,v = eig(a)
print('E-Value:', w)
print('E-Vector', v)

E-Value: [ 8.80916362  0.92620912 -0.73537273]
E-Vector [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


Exercise Session 3

In [ ]:
from PIL import Image
import numpy as np

# Membaca gambar dan mengubahnya menjadi array NumPy
img = Image.open('/content/sunsets girl.jpg').convert('L')
img_array = np.array(img)

# Mengubah ukuran matriks menjadi 9 x 9
img_resized = Image.fromarray(img_array).resize((9, 9))
img_resized_array = np.array(img_resized)

# Mencetak bentuk matriks
print('Bentuk matriks:', img_resized_array.shape)

# Menampilkan matriks
print('Matriks:')
print(img_resized_array)

Bentuk matriks: (9, 9)
Matriks:
[[16 16 17 17 16 17 16 17 17]
 [19 19 20 21 22 23 33 26 22]
 [20 23 27 30 29 53 65 29 21]
 [34 39 47 48 42 48 38 28 18]
 [38 63 84 87 77 65 52 35 25]
 [14 19 33 47 50 50 44 34 28]
 [14 14 15 22 19 25 28 23 21]
 [ 4  4  6 11  6 10 12  6  5]
 [ 4  5  5  6  7  4  4  4  3]]


In [ ]:
import numpy as np

In [ ]:
def normalize(x):
    fac = abs(x).max()
    x_n = x / x.max()
    return fac, x_n

Method 1

matrix 1 kiri atas

In [ ]:
x = np.array([1, 1, 1])
a = np.array([[16, 16, 17], [19, 19, 20], [20, 23, 27]])

for i in range(40):
  x = np.dot(a, x)
  labda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [0.68989705 0.8161051  1.        ]


matrix 2 tengah atas

In [ ]:
x = np.array([1,1,1])
a = np.array([[17, 16, 17], [21, 22, 23], [30, 29, 53]])

for i in range(20):
  x = np.dot(a, x)
  labda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [0.40211889 0.53641585 1.        ]


matrix 3 kanan atas

In [ ]:
x = np.array([1,1,1])
a = np.array([[16, 17, 17], [33, 26, 22], [65, 29, 21]])

for i in range(20):
  x = np.dot(a, x)
  labda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [0.50192863 0.77135523 1.        ]


matrix 4 tengah kiri

In [ ]:
x = np.array([1,1,1])
a = np.array([[34, 39, 47], [38, 63, 84], [14, 19, 33]])

for i in range(20):
  x = np.dot(a, x)
  labda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [0.66419661 1.         0.33827948]


matrix 5 tengah

In [ ]:
x = np.array([1,1,1])
a = np.array([[48, 42, 48], [87, 77, 65], [47, 50, 50]])

for i in range(20):
  x = np.dot(a, x)
  labda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [0.59480759 1.         0.64574827]


matrix 6 tengah kanan

In [ ]:
x = np.array([1,1,1])
a = np.array([[38, 28, 18], [52, 35, 25], [44, 34, 28]])

for i in range(20):
  x = np.dot(a, x)
  labda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [0.75284315 1.         0.95769549]


matrix 7 bawah kiri

In [ ]:
x = np.array([1,1,1])
a = np.array([[14, 14, 15], [4, 4, 6], [4, 5, 5]])

for i in range(20):
  x = np.dot(a, x)
  labda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [1.         0.30877418 0.30877418]


matrix 8 bawah tengah

In [ ]:
x = np.array([1,1,1])
a = np.array([[22, 19, 25], [11, 6, 10], [6, 7, 4]])

for i in range(20):
  x = np.dot(a, x)
  labda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [1.         0.4402042  0.27352128]


matrix 9 bawah kanan

In [ ]:
x = np.array([1,1,1])
a = np.array([[28, 23, 21], [12, 6, 5], [4, 4, 3]])

for i in range(20):
  x = np.dot(a, x)
  labda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [1.         0.37701385 0.14962109]


Method 2

matrix 1 kiri atas

In [ ]:
from numpy.linalg import inv
a = np.array([[16, 16, 17], [19, 19, 20], [20, 23, 27]])
a_inv = inv(a)

for i in range(20):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 15.671996732789667
Eigenvector: [-0.44789296  1.         -0.52131128]


matrix 2 atas tengah

In [ ]:
from numpy.linalg import inv
a = np.array([[17, 16, 17], [21, 22, 23], [30, 29, 53]])
a_inv = inv(a)

for i in range(20):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.040007312036975
Eigenvector: [-1.05534897  1.          0.05117739]


matrix 3 kanan atas

In [ ]:
from numpy.linalg import inv
a = np.array([[16, 17, 17], [33, 26, 22], [65, 29, 21]])
a_inv = inv(a)

for i in range(20):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 0.7733555262615098
Eigenvector: [-0.19380234  1.         -0.83233894]


matrix 4 tengah kiri

In [ ]:
from numpy.linalg import inv
a = np.array([[34, 39, 47], [38, 63, 84], [14, 19, 33]])
a_inv = inv(a)

for i in range(20):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 0.17534244804455992
Eigenvector: [-0.74470201  1.         -0.34521665]


matrix 5 tengah

In [ ]:
from numpy.linalg import inv
a = np.array([[48, 42, 48], [87, 77, 65], [47, 50, 50]])
a_inv = inv(a)

for i in range(20):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 0.2818332879215455
Eigenvector: [-0.43343427  1.         -0.54989264]


matrix 6 tengah kanan

In [ ]:
from numpy.linalg import inv
a = np.array([[38, 28, 18], [52, 35, 25], [44, 34, 28]])
a_inv = inv(a)

for i in range(20):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 0.9189829544497005
Eigenvector: [-0.5604243   1.         -0.31198429]


matrix 7 kiri bawah

In [ ]:
from numpy.linalg import inv
a = np.array([[14, 14, 15], [4, 4, 6], [4, 5, 5]])
a_inv = inv(a)

for i in range(20):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.4990320054819959
Eigenvector: [-0.45878828  1.         -0.49954994]


matrix 8 bawah tengah

In [ ]:
from numpy.linalg import inv
a = np.array([[22, 19, 25], [11, 6, 10], [6, 7, 4]])
a_inv = inv(a)

for i in range(20):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 0.37153513093329743
Eigenvector: [ 0.79582543 -2.15774068  1.        ]


matrix 9 bawah kanan

In [ ]:
from numpy.linalg import inv
a = np.array([[28, 23, 21], [12, 6, 5], [4, 4, 3]])
a_inv = inv(a)

for i in range(20):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)

print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

Eigenvalue: 1.2575842679194156
Eigenvector: [-0.39538021  1.         -0.54110128]
